<a href="https://colab.research.google.com/github/Gitronlee/DL_pytorch/blob/master/Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
from torch.autograd import Variable

x = Variable(torch.Tensor([5]), requires_grad = True)
w = Variable(torch.Tensor([6]), requires_grad = True)
b = Variable(torch.Tensor([7]), requires_grad = True)

y = w * x + b
y.backward()

print(x.grad)
print(w.grad)
print(b.grad)
x = torch.randn(3)
x = Variable(x,requires_grad = True)
y = x * 2
print(y)
y.backward(torch.FloatTensor([1, 0.1, 0.01]))#每个分量的梯度乘上1,0.1,0.01
print(x.grad)

tensor([6.])
tensor([5.])
tensor([1.])
